//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iServz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Application
    {
        public int ID { get; set; }
        public byte[] ID_FrontBack { get; set; }
        public int SP_ID { get; set; }
        public int SPA_Status_ID { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual SP_Application_Status SP_Application_Status { get; set; }
    }
}
