//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iServz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SR_Line()
        {
            this.SQ_Line = new HashSet<SQ_Line>();
        }
    
        public int ID { get; set; }
        public int Service_ID { get; set; }
        public int SR_ID { get; set; }
        public int Image_ID { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQ_Line> SQ_Line { get; set; }
    }
}
