//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservzz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> ConsID { get; set; }
        public Nullable<int> SP_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Consumer Consumer { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
