//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservzz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetServicesEntities : DbContext
    {
        public InternetServicesEntities()
            : base("name=InternetServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChargeItem> ChargeItems { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceOrder> ServiceOrders { get; set; }
        public virtual DbSet<ServiceOrderLine> ServiceOrderLines { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<ServiceQuote> ServiceQuotes { get; set; }
        public virtual DbSet<ServiceQuoteStatu> ServiceQuoteStatus { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<SO_Status> SO_Status { get; set; }
        public virtual DbSet<SP_Application> SP_Application { get; set; }
        public virtual DbSet<SP_Application_Status> SP_Application_Status { get; set; }
        public virtual DbSet<SP_Status> SP_Status { get; set; }
        public virtual DbSet<SQ_Line> SQ_Line { get; set; }
        public virtual DbSet<SR_Line> SR_Line { get; set; }
        public virtual DbSet<SR_Status> SR_Status { get; set; }
        public virtual DbSet<Surburb> Surburbs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Utility> Utilities { get; set; }
    }
}
