//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservzz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderLine
    {
        public int ID { get; set; }
        public int SO_ID { get; set; }
        public int Service_ID { get; set; }
        public Nullable<int> SQ_ID { get; set; }
        public Nullable<int> SQL_ID { get; set; }
        public Nullable<int> Material_ID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ServiceQuote ServiceQuote { get; set; }
        public virtual SQ_Line SQ_Line { get; set; }
    }
}
